/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { useCustomization } from "../contexts/Customization";

function MugModel(props) {
  const { nodes, materials } = useGLTF("./models//MugModel.gltf");
  const { material, legs, chairColor, cushionColor } = useCustomization();

  // Modifiez le matériau d'origine pour appliquer la couleur personnalisée.
  materials["color-material"].color.set(chairColor.color);

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.412, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.Material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["color-material"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Exterior.geometry}
        material={materials["white-material"]}
        rotation={[0, -0.412, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Impression.geometry}
        material={materials["map-material"]}
        rotation={[0, -0.412, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior.geometry}
        material={materials["color-material"]}
        rotation={[0, -0.412, 0]}
      />
    </group>
  );
}

export default MugModel;

useGLTF.preload("./models//MugModel.gltf");